// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHUWgNU9ty1IMaaZ7ZHaIoFymzYtY5-90',
    appId: '1:69423423467:web:bd45f0eef48d9c130ac3ae',
    messagingSenderId: '69423423467',
    projectId: 'test-app-1264e',
    authDomain: 'test-app-1264e.firebaseapp.com',
    databaseURL: 'https://test-app-1264e-default-rtdb.firebaseio.com',
    storageBucket: 'test-app-1264e.appspot.com',
    measurementId: 'G-HPBSNQ4HZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCujLVad32DsHfTKrSKibFsU8wO6UTexWg',
    appId: '1:69423423467:android:ecc6ea4817cb4c300ac3ae',
    messagingSenderId: '69423423467',
    projectId: 'test-app-1264e',
    databaseURL: 'https://test-app-1264e-default-rtdb.firebaseio.com',
    storageBucket: 'test-app-1264e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoDtmuuKAnwmJrB98O0ObG_989JEI131c',
    appId: '1:69423423467:ios:73015b51bb7240290ac3ae',
    messagingSenderId: '69423423467',
    projectId: 'test-app-1264e',
    databaseURL: 'https://test-app-1264e-default-rtdb.firebaseio.com',
    storageBucket: 'test-app-1264e.appspot.com',
    iosClientId: '69423423467-u5muv3m095j2040dt6dnan7hms00486d.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoDtmuuKAnwmJrB98O0ObG_989JEI131c',
    appId: '1:69423423467:ios:73015b51bb7240290ac3ae',
    messagingSenderId: '69423423467',
    projectId: 'test-app-1264e',
    databaseURL: 'https://test-app-1264e-default-rtdb.firebaseio.com',
    storageBucket: 'test-app-1264e.appspot.com',
    iosClientId: '69423423467-u5muv3m095j2040dt6dnan7hms00486d.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthDemo',
  );
}
